### ISSUE TITLE
luci2-ui-base-2018-06-12 build failed on Ubuntu 18.04, Thanks

### ISSUE THREAD

**Issue by ballzb** [jow-/luci-ng#51]
make[3]: Entering directory '/home/lab/samba/zhangbo/18.06/feeds/luci2/luci2-ui-base'
rm -f /home/lab/samba/zhangbo/18.06/build_dir/target-mips_24kc_musl/luci2-ui-base-2018-06-12-2c1116a/.built
touch /home/lab/samba/zhangbo/18.06/build_dir/target-mips_24kc_musl/luci2-ui-base-2018-06-12-2c1116a/.built_check
make -C /home/lab/samba/zhangbo/18.06/build_dir/target-mips_24kc_musl/luci2-ui-base-2018-06-12-2c1116a
make[4]: Entering directory '/home/lab/samba/zhangbo/18.06/build_dir/target-mips_24kc_musl/luci2-ui-base-2018-06-12-2c1116a'
node ./node_modules/.bin/gulp dist
[09:34:53] Using gulpfile ~/samba/zhangbo/18.06/build_dir/target-mips_24kc_musl/luci2-ui-base-2018-06-12-2c1116a/gulpfile.js
[09:34:53] Starting 'dist'...
[09:34:53] Starting 'svg'...
[09:34:53] Starting 'copyAssets'...
[09:34:53] Starting 'svgExtractIcons'...
[09:34:53] Starting 'lintErr'...
gulp-search :  [ 'md-svg-icon="router-wireless"' ]
gulp-search :  null
[09:34:54] 'lintErr' errored after 372 ms
[09:34:54] Error: Syntax error in selector "angular:animation" at position 8: Expected "declaration", "expression", "function", "pattern" or "statement" but "a" found.
    at tryParseSelector (/home/lab/samba/zhangbo/18.06/build_dir/target-mips_24kc_musl/luci2-ui-base-2018-06-12-2c1116a/node_modules/eslint/lib/util/node-event-generator.js:163:19)
    at lodash.memoize.rawSelector (/home/lab/samba/zhangbo/18.06/build_dir/target-mips_24kc_musl/luci2-ui-base-2018-06-12-2c1116a/node_modules/eslint/lib/util/node-event-generator.js:175:28)
    at memoized (/home/lab/samba/zhangbo/18.06/build_dir/target-mips_24kc_musl/luci2-ui-base-2018-06-12-2c1116a/node_modules/eslint/node_modules/lodash/lodash.js:10551:27)
    at NodeEventGenerator.eventNames.forEach.rawSelector (/home/lab/samba/zhangbo/18.06/build_dir/target-mips_24kc_musl/luci2-ui-base-2018-06-12-2c1116a/node_modules/eslint/lib/util/node-event-generator.js:235:30)
    at Array.forEach (<anonymous>)
    at new NodeEventGenerator (/home/lab/samba/zhangbo/18.06/build_dir/target-mips_24kc_musl/luci2-ui-base-2018-06-12-2c1116a/node_modules/eslint/lib/util/node-event-generator.js:234:20)
    at EventEmitter.module.exports.api.verify (/home/lab/samba/zhangbo/18.06/build_dir/target-mips_24kc_musl/luci2-ui-base-2018-06-12-2c1116a/node_modules/eslint/lib/eslint.js:915:34)
    at processText (/home/lab/samba/zhangbo/18.06/build_dir/target-mips_24kc_musl/luci2-ui-base-2018-06-12-2c1116a/node_modules/eslint/lib/cli-engine.js:264:31)
    at CLIEngine.executeOnText (/home/lab/samba/zhangbo/18.06/build_dir/target-mips_24kc_musl/luci2-ui-base-2018-06-12-2c1116a/node_modules/eslint/lib/cli-engine.js:754:26)
    at verify (/home/lab/samba/zhangbo/18.06/build_dir/target-mips_24kc_musl/luci2-ui-base-2018-06-12-2c1116a/node_modules/gulp-eslint/index.js:20:25)
[09:34:54] 'dist' errored after 383 ms
[09:34:54] The following tasks did not complete: svg, copyAssets, svgExtractIcons
[09:34:54] Did you forget to signal async completion?
Makefile:30: recipe for target 'build' failed
make[4]: *** [build] Error 1
make[4]: Leaving directory '/home/lab/samba/zhangbo/18.06/build_dir/target-mips_24kc_musl/luci2-ui-base-2018-06-12-2c1116a'
Makefile:77: recipe for target '/home/lab/samba/zhangbo/18.06/build_dir/target-mips_24kc_musl/luci2-ui-base-2018-06-12-2c1116a/.built' failed
make[3]: *** [/home/lab/samba/zhangbo/18.06/build_dir/target-mips_24kc_musl/luci2-ui-base-2018-06-12-2c1116a/.built] Error 2
make[3]: Leaving directory '/home/lab/samba/zhangbo/18.06/feeds/luci2/luci2-ui-base'
Command exited with non-zero status 2
time: package/feeds/luci2/luci2-ui-base/compile#1.25#0.13#1.25
package/Makefile:107: recipe for target 'package/feeds/luci2/luci2-ui-base/compile' failed
make[2]: *** [package/feeds/luci2/luci2-ui-base/compile] Error 2
make[2]: Leaving directory '/home/lab/samba/zhangbo/18.06'
package/Makefile:103: recipe for target '/home/lab/samba/zhangbo/18.06/staging_dir/target-mips_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/home/lab/samba/zhangbo/18.06/staging_dir/target-mips_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/lab/samba/zhangbo/18.06'
/home/lab/samba/zhangbo/18.06/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by ballzb** [comment]
[package.json.zip](https://github.com/jow-/luci-ng/files/2169169/package.json.zip)
upgrade eslint-plugin-angular to 1.6.3 will  fix this issue.
