### ISSUE TITLE
Build Failed on Openwrt 19.07.7

### ISSUE THREAD

**Issue by zhanghua000** [jow-/luci-ng#77]
Build System Output:
```
make[4]: Entering directory '/home/zhanghua/openwrt/build_dir/target-mips_24kc_musl/luci2-ui-core-20200227'
npm run gen-schema

> luci2-ui-core@0.0.1 gen-schema
> rx-json-ui g -r -p ./src/tsconfig.app.json -m app/app.module#AppModule out/widgetschema

Compiling application...
Compiled OK
Found 42 widgets from 5 transitive modules
Generating schemas 1/42/home/zhanghua/openwrt/build_dir/target-mips_24kc_musl/luci2-ui-core-20200227/node_modules/typescript-json-schema/dist/typescript-json-schema.js:877
            throw new Error("type " + symbolName + " not found");
            ^

Error: type SetChartWidgetComponent not found
    at JsonSchemaGenerator.getSchemaForSymbol (/home/zhanghua/openwrt/build_dir/target-mips_24kc_musl/luci2-ui-core-20200227/node_modules/typescript-json-schema/dist/typescript-json-schema.js:877:19)
    at /home/zhanghua/openwrt/build_dir/target-mips_24kc_musl/luci2-ui-core-20200227/node_modules/rx-json-ui-cli/dist/public-api.js:82:37
    at Array.forEach (<anonymous>)
    at generateSchemas (/home/zhanghua/openwrt/build_dir/target-mips_24kc_musl/luci2-ui-core-20200227/node_modules/rx-json-ui-cli/dist/public-api.js:80:13)
    at Command.generate (/home/zhanghua/openwrt/build_dir/target-mips_24kc_musl/luci2-ui-core-20200227/node_modules/rx-json-ui-cli/dist/public-api.js:325:5)
    at Command.listener [as _actionHandler] (/home/zhanghua/openwrt/build_dir/target-mips_24kc_musl/luci2-ui-core-20200227/node_modules/rx-json-ui-cli/node_modules/commander/index.js:426:31)
    at Command._parseCommand (/home/zhanghua/openwrt/build_dir/target-mips_24kc_musl/luci2-ui-core-20200227/node_modules/rx-json-ui-cli/node_modules/commander/index.js:1002:14)
    at Command._dispatchSubcommand (/home/zhanghua/openwrt/build_dir/target-mips_24kc_musl/luci2-ui-core-20200227/node_modules/rx-json-ui-cli/node_modules/commander/index.js:953:18)
    at Command._parseCommand (/home/zhanghua/openwrt/build_dir/target-mips_24kc_musl/luci2-ui-core-20200227/node_modules/rx-json-ui-cli/node_modules/commander/index.js:970:12)
    at Command.parse (/home/zhanghua/openwrt/build_dir/target-mips_24kc_musl/luci2-ui-core-20200227/node_modules/rx-json-ui-cli/node_modules/commander/index.js:801:10)
npm ERR! code 1
npm ERR! path /home/zhanghua/openwrt/build_dir/target-mips_24kc_musl/luci2-ui-core-20200227
npm ERR! command failed
npm ERR! command sh -c rx-json-ui g -r -p ./src/tsconfig.app.json -m app/app.module#AppModule out/widgetschema

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zhanghua/.npm/_logs/2021-03-14T03_53_48_068Z-debug.log
make[4]: *** [Makefile:18: build] Error 1
make[4]: Leaving directory '/home/zhanghua/openwrt/build_dir/target-mips_24kc_musl/luci2-ui-core-20200227'
make[3]: *** [Makefile:72: /home/zhanghua/openwrt/build_dir/target-mips_24kc_musl/luci2-ui-core-20200227/.built] Error 2
make[3]: Leaving directory '/home/zhanghua/openwrt/feeds/luci2/luci2-ui-core'
time: package/feeds/luci2/luci2-ui-core/compile#13.10#0.74#8.24
make[2]: *** [package/Makefile:113: package/feeds/luci2/luci2-ui-core/compile] Error 2
make[2]: Leaving directory '/home/zhanghua/openwrt'
make[1]: *** [package/Makefile:107: /home/zhanghua/openwrt/staging_dir/target-mips_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/zhanghua/openwrt'
make: *** [/home/zhanghua/openwrt/include/toplevel.mk:227: world] Error 2
```
I am building firmware using nodejs on my host which nodejs version is 15.11.0 and Linux distribution is Arch Linux
Output of `npm version`:
```shell
$ npm version
{
  npm: '7.6.3',
  node: '15.11.0',
  v8: '8.6.395.17-node.27',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '88',
  nghttp2: '1.41.0',
  napi: '7',
  llhttp: '2.1.3',
  openssl: '1.1.1j',
  cldr: '38.1',
  icu: '68.2',
  tz: '2020d',
  unicode: '13.0'
}
```
Thank you in advance for your help.

**Comment by monstery** [comment]
I also met this problem in Ubuntu 14.04 64-bit Linux distribution
{
  npm: '6.14.12',
  ares: '1.16.1',
  brotli: '1.0.9',
  cldr: '37.0',
  http_parser: '2.9.4',
  icu: '67.1',
  llhttp: '2.1.3',
  modules: '72',
  napi: '8',
  nghttp2: '1.41.0',
  node: '12.22.1',
  openssl: '1.1.1k',
  tz: '2019c',
  unicode: '13.0',
  uv: '1.40.0',
  v8: '7.8.279.23-node.46',
  zlib: '1.2.11'
}

$ nodejs -v
v12.22.1
